remote_theme: rundocs/jekyll-rtd-theme
title: OpenBMP

lang: en
description: OpenBMP Documentation
url: "https://www.openbmp.org"
lang: en

lsi: true
safe: true

readme_index:
  with_frontmatter: true

show_sorted: false

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-mentions
